---
- name: Deploy Mysql/Httpd/Wordpress
  hosts:  137.74.107.136
  become: true
  roles:
    - { role:  dimsdev.mysql, tags: mysql }
    - { role:  dimsdev.httpd, tags: web }
    - { role:  dimsdev.wordpress, tags: wordpress }

