---

- name: adding epel repo
  package: name={{item}} state=installed
  with_items:
    - epel-release

- name: adding mysql/mariadb packages
  package: name={{item}} state=installed
  with_items:
    - mariadb-server
    - MySQL-python 

- name: start mariadb
  service: name=mysqld state=started enabled=yes

- name: Generate new root password
  command: openssl rand -hex 7 creates=/root/.my.cnf
  register: mysql_new_root_pass

- name: set the root password
  mysql_user: name=root host="{{item}}"
              password={{ mysql_new_root_pass.stdout }}
              priv=*.*:ALL,GRANT
              login_user=root
              login_password=""
              state=present
  with_items:
    - "{{inventory_hostname}}"
    - localhost
    - 127.0.0.1
    - ::1

- name: write the index file
  template: src=my.cnf.j2 dest=/root/.my.cnf mode=0600

- name: Output new root password
  debug: msg="New root password is {{ mysql_new_root_pass.stdout }} "
  when: mysql_new_root_pass.changed


- name: Remove anonymous users
  mysql_user: name="" state=absent
  when:  mysql_new_root_pass.changed
  ignore_errors: yes

- name: Remove test database 
  mysql_db: name=test state=absent
  when: mysql_new_root_pass.changed
  ignore_errors: yes


- name: set bind-address to default ipv4 in my.conf file
  lineinfile: dest=/etc/my.cnf line=bind-address={{ansible_default_ipv4.address}} state=present insertafter='^\[mysqld\]'
  notify: restart mysql

#- name: configuring firewall services
#  firewalld: service={{item}} permanent=true state=enabled
#  with_items:
#    - mysql

#- name: reloading the firewall
#  command: firewall-cmd --reload
